### dash_social.get_utp_name(date,parameter)
  CASE
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_ipt|_famipt|_IT-ipt|_ipt.lgt|_ipt.legko|_ipt.transh|_ipt1R|_fam.mltry.ipt|_ipt.lgt|_dom.otdel-IT-ipt|_kv-life-ipt|_war-ipt|_ipt-minpay|_dig-ipt') THEN 'Ипотека'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_dom.mbl-minpay|_dom.otdel-minpay') THEN 'Мин платеж'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_bron|_st.sale|_newkorp|_new-kv|_new-apart') THEN 'Старт продаж'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_minprice|_ski-minprice|_kv.mck-minprice|_kv.nab-minprice|_mbl-minprice-yug|_mbl-minprice-cl-yug|_kv.centr-minprice|_dom.home-appl-minprice|_kv.metro-minprice|_dom.home-appl-rassr-minprice|_kv.otdel-minprice|_mbl-minprice|_dom.otdel-city-nov.sh-minprice|_dom.otdel-comfort-full.life-minprice|_dom.otdel-frame-minprice|_dom.otdel-stone-minprice|_dom.water-minprice|_dom.shale-minprice|_dom.otdel-minprice|_dom.mbl-city.infr-minprice|_dom.mbl-minprice|_start-minprice|_start-minpay|_ap.mbl-minprice|_apart.ot-minprice|_apart.bk-minprice|_reka-minprice|_kv-life-minprice|_no.otdel-minprice|_key24.minprice|_1minprice|_2minprice|_ap.2minprice|_2k-life-minprice') THEN 'Минимальная стоимость'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_apart.bk') THEN 'Аппартаменты'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_sdacha24|_sdacha25|_zas24|_zas25|_key24|_key25|_zasel-srazy|_zasel-srazy-pvz|_dom.key') THEN 'Ключи в '
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_mbl|_dom.mbl-key|_2mbl|_dom.mbl') THEN 'С мебелью'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_kuxn') THEN 'С кухней'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_kv.otdel') THEN 'С отделкой'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_ap.park|_ap.dt.sad') THEN 'Рядом с'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_dom.dod|_dod|_1-11-klass|_curriculum|_personal-plan|_20students|_private-educ|_invitation|_school-present') THEN 'Самолетум'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_dobavim|_mbl.gift|_gifts') THEN 'Подарки'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_dom.home-appl-sale|_sale|_flash|_sale-y-par') THEN 'Скидка'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_rassr|_dom.mbl-rassr') THEN 'Рассрочка'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_kv-life-vgd|_vgd') THEN 'Выгода'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_dom.dt.sad|_sch-2dt.sad|_sch-dt.sad') THEN 'Детский сад и Школа'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_prest-area|_forest-zal|_reka-view|_reka|_dom.water|_kv.centr|_kv.krml|_b.centr|_kv.b.centr|_fin.zal|_city.infr|_beach|_sadovoe|_izhs|_izhs-safety|_izhs-calm') THEN 'ГЕО'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_cashback-travel|_cshbck-tbank') THEN 'Кэшбек'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_pvz') THEN 'Первый взнос'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_bez-pvz|_kv.centr-bez-pvz|_real-bez-pvz|_kv.b.centr-bez-pvz') THEN 'Без ПВЗ'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_before-after') THEN 'До-После'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_ready-kv') THEN 'Готовые квартиры'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_rent-vgd|_rent|_rent-wint') THEN 'Аренда'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_stud-msk|_prep-sess|_first-kv-own|_hw') THEN 'Студенты'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_clprt-fast') THEN 'Целепорт'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_mozh') THEN 'Можнотека'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_invst') THEN 'Инвестиции'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_fransh') THEN 'Франшиза'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_metr') THEN 'Метр от Самолет'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_trade') THEN 'trade-in'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_free-reс|_10rec') THEN 'Рекомендации'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_comfort|_wheel|_zak.dvor|_smart-tech|_home-appl|_terrace|_dom.shale|_private-ter') THEN 'Продуктовые'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_none') THEN 'Ничего'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_get-first|_book-fix-cost|_otklad|_save-up-faster|_sp.pur|_choose-now|_nakop') THEN 'Мотивация'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_kv.wnt2cmback|_paris') THEN 'Вернуться в квартиру'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_offer|_responsibility|_wishes|_naves-avto|_energy-for-life|_full.life|_mbl-teplo|_mbl-wth|_samokot|_flamingo|_14feb|_sravny|_happy') THEN 'Другое'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_full-own|_wisk-paws-tail|_transp-cond|_free-meal-c|_free-meal-b') THEN 'petsflats'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_kv-for-life') THEN 'Квартиры для жизни'
    WHEN REGEXP_CONTAINS(LOWER(parameter),r'_kv.metro|_kv.mck|_ap.metro|_kv.mcd|_ap.mck|_ap.mcd|_apart.pyatn.sh|_dom.nov.sh') THEN 'Транспортная инфраструктура'
  END