### dash_custom.get_utp(ad_name)
  CASE
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'ipt') THEN 'Ипотека'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_rassr') THEN 'Рассрочка'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_sale') THEN 'Скидка'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_mozh') THEN 'Можнотека'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'minprice') THEN 'Минимальная цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'minpay') THEN 'Минимальный платеж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_invst') THEN 'Инвестиции'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_fransh') THEN 'Франшиза'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_metr') THEN 'Метр от Самолет'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_trade') THEN 'trade-in'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_vgd') THEN 'Выгода до Х'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_none') THEN 'Ничего'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_new') THEN 'Новые квартиры / апарты'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_bron') THEN 'Старт бронирования'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_st.sale') THEN 'Старт продаж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_newkorp') THEN 'Новый корпус'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_start') THEN 'Cтарт продаж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_sdacha') THEN 'Сдача дома'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_samokot') THEN 'Самокот'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_flamingo') THEN 'Фламинго СММ'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_zas') THEN 'Заселение'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_key') THEN 'Выдача ключей'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mbl') THEN 'Квартиры с мебелью'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'kuxn') THEN 'Кватиры с кухней'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'otdel') THEN 'Отделка'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'park') THEN 'Парк'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'metro') THEN 'Метро'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'dt.sad') THEN 'Детский сад'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mck') THEN 'МЦК'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mcd') THEN 'МЦД'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'otdel-minprice') THEN 'Отделка + мин цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mbl-minprice') THEN 'Мебель + мин цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mbl-minpay') THEN 'Мебель + мин платеж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'otdel-minpay') THEN 'Отделка + мин платеж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'centr-minprice') THEN 'Центр + мин цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'centr-minpay') THEN 'Центра + мин платеж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'metro-minprice') THEN 'Метро + мин цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'metro-minpay') THEN 'Метро + мин платеж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mck-minprice') THEN 'МЦК + мин цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'mck-minpay') THEN 'МЦК + мин платеж'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_curriculum') THEN 'Кружки и секции'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_personal-plan') THEN 'Песональный учебный план'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_20students') THEN 'Не более 20 учеников'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_bez-pvz') THEN 'Без взноса пвз'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_dobavim') THEN 'Добавим до Х%'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_nakop') THEN 'Накопить на квартиру'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_dod') THEN 'День открытых дверей'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_1-11-klass') THEN '1-11 классы'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_invitation') THEN 'Приглашаем на ДОД'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_school-present') THEN 'Презентация школы'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_14feb') THEN '14 февраля'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_free-reс') THEN 'бесплатные рекомендации'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_10rec') THEN '10 рекомендаций'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_sravny') THEN 'Сравнить с похожими людьми'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_happy') THEN 'Исследование счастья'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'_flash') THEN 'Flash-sale'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'apart.ot-14.5') THEN 'Минимальная цена'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'apart.bk|apart.pyatn.sh') THEN 'Апартаменты'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'obsh-3.9|obsh0') THEN 'Общий посыл'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'private-ter') THEN 'Приватная территория'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'reka') THEN 'Река'
    WHEN REGEXP_CONTAINS(LOWER(ad_name),r'terrace') THEN 'Терасса'
  END