### agg_procedures.get_placement`(date,ct_source,ct_medium,crm_advertising_source,utm_source,utm_medium,utm_campaign,utm_content,utm_term)
  CASE
    ### Контекст
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'context_yandex_google') AND LOWER(utm_medium) = 'calls' THEN 'Визитка'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'yandex') AND utm_medium = 'cpc' THEN 'Yandex'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'google') AND utm_medium = 'cpc' THEN 'Google Ads'

    ### Базы
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mediapronet-avito') AND LOWER(utm_medium) = 'calls' THEN 'Авито/mediapronet'
    WHEN LOWER(crm_advertising_source) = 'mediapronet avito' THEN 'Авито/mediapronet'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'aquarius-na100pro$') AND LOWER(utm_medium) = 'calls' THEN 'Аквариум/NA100PRO'
    WHEN LOWER(crm_advertising_source) = 'аквариус na100pro' THEN 'Аквариум/NA100PRO'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mediapronet-cian') AND LOWER(utm_medium) = 'calls' THEN 'Cian/mediapronet'
    WHEN LOWER(crm_advertising_source) = 'mediapronet cian' THEN 'Cian/mediapronet'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mediapronet-m2') AND LOWER(utm_medium) = 'calls' THEN 'M2.RU/mediapronet'
    WHEN LOWER(crm_advertising_source) = 'mediapronet m2' THEN 'M2.RU/mediapronet'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mediapronet-yandex_realty.ru') AND LOWER(utm_medium) = 'calls' THEN 'Yandex.Realty.Ru/mediapronet'
    WHEN LOWER(crm_advertising_source) = 'mediapronet яндекс недвиж' THEN 'Yandex.Realty.Ru/mediapronet'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'basic_xml') AND LOWER(utm_medium) IN ('calls','cpl') THEN 'Basic XML'
    WHEN LOWER(crm_advertising_source) = 'basic xml' THEN 'Basic XML'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'aquarius') AND LOWER(utm_medium) = 'calls' THEN 'Другое'
    WHEN REGEXP_CONTAINS(LOWER(crm_advertising_source),r'аквариус') THEN 'Другое'

    ### Лидогенераторы
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'atommedia') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'Atommedia'
    WHEN LOWER(crm_advertising_source) = 'atommedia лид' THEN 'Atommedia'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'call.of.leads|callofleads') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'Call of Leads'
    WHEN LOWER(crm_advertising_source) = 'call of leads лид' THEN 'Call of Leads'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'callexchange') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'Callexchange'
    WHEN LOWER(crm_advertising_source) = 'callexchange' THEN 'Callexchange'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'callrealty') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'CallRealty'
    WHEN LOWER(crm_advertising_source) = 'callrealty лид' THEN 'CallRealty'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'calltact') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'CallTact'
    WHEN LOWER(crm_advertising_source) = 'calltact лид' THEN 'CallTact'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'cpaexchange') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'CPAExchange'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'datavision') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'DataVision'
    WHEN LOWER(crm_advertising_source) = 'datavision лид' THEN 'DataVision'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'getflat') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'GetFlat'
    WHEN LOWER(crm_advertising_source) = 'getflat лид' THEN 'GetFlat'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'like_estate|likeestate') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'LikeEstate'
    WHEN LOWER(crm_advertising_source) = 'like estate лид' THEN 'LikeEstate'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'maketrue') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'MakeTrue'
    WHEN LOWER(crm_advertising_source) = 'maketrue лид' THEN 'MakeTrue'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'marketcall') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'MarketCall'
    WHEN LOWER(crm_advertising_source) = 'maketrue лид' THEN 'MarketCall'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'monkey') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'Monkey'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'rocketad') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'Rocketad'
    WHEN LOWER(crm_advertising_source) = 'roketad лид' THEN 'Rocketad'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'roombery|roomberry') AND LOWER(utm_medium) IN ('calls','cpa') THEN 'Roomberry'
    WHEN LOWER(crm_advertising_source) = 'roombery лид' THEN 'Roomberry'

    ### Программатик
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'getflat') AND LOWER(utm_medium) = 'cpm' THEN 'Getflat'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'hybrid') AND LOWER(utm_medium) = 'cpm' THEN 'Hybrid'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'premium_id') AND LOWER(utm_medium) = 'cpm' THEN 'Premium ID'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'smart_data_premium') AND LOWER(utm_medium) = 'cpm' THEN 'Smart Data Premium'
    WHEN LOWER(crm_advertising_source) = 'smartdata программатик премиум' THEN 'Smart Data Premium'

    ### Охватные ресурсы
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'2gis') AND LOWER(utm_medium) IN ('calls','statika') THEN '2gis.ru'
    WHEN LOWER(crm_advertising_source) = '2gis' THEN '2gis.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'yandex.maps|navigator|yandex.ru_karty_navigator|yandex_geoservice') AND LOWER(utm_medium) IN ('calls','statika','kartochka','cpm') THEN 'Яндекс Геосервисы'
    WHEN LOWER(crm_advertising_source) = 'yandex.ru карты и навигатор' THEN 'Яндекс Геосервисы'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'realty.yandex|yandex.ru_spravochnik') AND LOWER(utm_medium) IN ('calls','cpm') THEN 'Яндекс Недвижимость'
    WHEN LOWER(crm_advertising_source) = 'yandex.ru справочник' THEN 'Яндекс Недвижимость'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'google.maps|google.com_karty') AND LOWER(utm_medium) IN ('calls','kartochka') THEN 'google.com карты'
    WHEN LOWER(crm_advertising_source) = 'google.com карты' THEN 'google.com карты'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'afisha') AND LOWER(utm_medium) = 'cpm' THEN 'Afisha Daily'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'bfm') AND LOWER(utm_medium) = 'cpm' THEN 'BFM.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'cian') AND LOWER(utm_medium) = 'cpm' THEN 'Cian.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'forbes') AND LOWER(utm_medium) = 'cpm' THEN 'Forbes'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'megafon') AND LOWER(utm_medium) = 'push' THEN 'Megafon '
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'interpool') AND LOWER(utm_medium) IN ('push','cpm') THEN 'Interpool'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'kommersant') AND LOWER(utm_medium) = 'cpm' THEN 'Kommersant'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'lenta') AND LOWER(utm_medium) = 'cpm' THEN 'Lenta'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mts') AND LOWER(utm_medium) = 'push' THEN 'MTS'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'one_target') AND LOWER(utm_medium) = 'cpm' THEN 'One Target'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'rbc') AND LOWER(utm_medium) = 'cpm' THEN 'RBC'
    WHEN LOWER(crm_advertising_source) = 'rbc.ru баннер' THEN 'RBC'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'timeout') AND LOWER(utm_medium) = 'cpm' THEN 'Timeout.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'vc_desktop|vc_mobile|vc.ru') AND LOWER(utm_medium) = 'cpm' THEN 'VC'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'vedomosti') AND LOWER(utm_medium) = 'cpm' THEN 'Vedomosti.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'incrussia') AND LOWER(utm_medium) = 'push' THEN 'Incrussia'

    ### Тематические площадки
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'101novostroyka') AND LOWER(utm_medium) IN ('calls','statika') THEN '101novostroyka.ru'
    WHEN LOWER(crm_advertising_source) = '101novostroyka.ru тгб' THEN '101novostroyka.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'1dom') AND LOWER(utm_medium) = 'statika' THEN '1dom.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'aurumrealty') AND LOWER(utm_medium) IN ('calls','statika') THEN 'aurumrealty.ru'
    WHEN LOWER(crm_advertising_source) = 'aurumrealty.ru тгб' THEN 'aurumrealty.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'avaho') AND LOWER(utm_medium) IN ('calls','statika') THEN 'avaho.ru'
    WHEN LOWER(crm_advertising_source) = 'avaho.ru тгб' THEN 'avaho.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'businessclass.moscow') AND LOWER(utm_medium) IN ('calls','statika') THEN 'Businessclass.moscow'
    WHEN LOWER(crm_advertising_source) IN ('businessclass.moscow баннер','businessclass.moscow тгб') THEN 'Businessclass.moscow'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'dommsk') AND LOWER(utm_medium) IN ('calls','statika','cpm') THEN 'dommsk.ru'
    WHEN LOWER(crm_advertising_source) = 'dommsk.ru тгб' THEN 'dommsk.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'gogethome') AND LOWER(utm_medium) IN ('cpm','statika') THEN 'gogethome.ru'
    WHEN LOWER(crm_advertising_source) = 'gogethome.ru баннер' THEN 'gogethome.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'kdo') AND LOWER(utm_medium) = 'statika' THEN 'kdo.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'kvartyroom') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'Kvartyroom'
    WHEN LOWER(crm_advertising_source) = 'kvartyroom.ru тгб' THEN 'Kvartyroom'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'lifedeluxe') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'lifedeluxe.ru'
    WHEN LOWER(crm_advertising_source) = 'lifedeluxe.ru тгб' THEN 'lifedeluxe.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mosdom') AND LOWER(utm_medium) IN ('cpm','statika') THEN 'mosdom.su'
    WHEN LOWER(crm_advertising_source) = 'mosdom.ru тгб' THEN 'mosdom.su'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'move') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'move.ru'
    WHEN LOWER(crm_advertising_source) = 'move.ru спецпроект' THEN 'move.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'msk-novostroyki') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'msk-novostroyki.ru'
    WHEN LOWER(crm_advertising_source) = 'msk-novostroyki.ru тгб' THEN 'msk-novostroyki.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'myburg.su') AND LOWER(utm_medium) = 'cpm' THEN 'myburg.su'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'myburg') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'myburg.ru'
    WHEN LOWER(crm_advertising_source) = 'myburg.ru тгб' THEN 'myburg.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novomoscow') AND LOWER(utm_medium) IN ('calls','statika') THEN 'novomoscow.ru'
    WHEN LOWER(crm_advertising_source) = 'novomoscow.ru тгб' THEN 'novomoscow.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroev') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'Novostroev.ru'
    WHEN LOWER(crm_advertising_source) = 'novostroev.ru баннер' THEN 'Novostroev.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroy-gid') AND LOWER(utm_medium) = 'statika' THEN 'Novostroy-gid.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroy-m') AND LOWER(utm_medium) IN ('calls','statika') THEN 'novostroy-m.ru'
    WHEN LOWER(crm_advertising_source) IN ('novostroy-m.ru спецпроект','novostroy-m.ru спецпредложение') THEN 'novostroy-m.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroycity') AND LOWER(utm_medium) IN ('cpm','statika') THEN 'novostroycity.ru'
    WHEN LOWER(crm_advertising_source) = 'novostroycity.ru тгб' THEN 'novostroycity.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'poisk-novostroyki') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'Poisk-Novostroyki.ru'
    WHEN LOWER(crm_advertising_source) = 'poisk-novostroyki.ru тгб' THEN 'Poisk-Novostroyki.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroy') AND LOWER(utm_medium) = 'cpm' THEN 'novostroy'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'realestate') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'RealEstate.ru'
    WHEN LOWER(crm_advertising_source) = 'realestate.ru тгб' THEN 'RealEstate.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'realtymag') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'realtymag.ru'
    WHEN LOWER(crm_advertising_source) = 'realtymag.ru тгб' THEN 'realtymag.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'realtystreet') AND LOWER(utm_medium) = 'statika' THEN 'Realtystreet.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'russianrealty') AND LOWER(utm_medium) IN ('calls','statika') THEN 'Russianrealty.ru'
    WHEN LOWER(crm_advertising_source) = 'russianrealty.ru тгб' THEN 'Russianrealty.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'2realty') AND LOWER(utm_medium) = 'statika' THEN '2realty.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'realty') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'realty.ru'
    WHEN LOWER(crm_advertising_source) = 'realty.ru баннер' THEN 'realty.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'reforum') AND LOWER(utm_medium) = 'statika' THEN 'Reforum.ru'
    WHEN LOWER(crm_advertising_source) = 'reforum.ru тгб' THEN 'Reforum.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'rendv') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'Rendv.ru'
    WHEN LOWER(crm_advertising_source) = 'rendv.ru тгб' THEN 'Rendv.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'restate') AND LOWER(utm_medium) IN ('calls','statika') THEN 'Restate.ru'
    WHEN LOWER(crm_advertising_source) = 'restate.ru спецпроект' THEN 'Restate.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'stroynov') AND LOWER(utm_medium) IN ('cpm','calls','statika') THEN 'Stroynov.ru'
    WHEN LOWER(crm_advertising_source) = 'stroynov спецпроект' THEN 'Stroynov.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'topnovostroek') AND LOWER(utm_medium) IN ('calls','statika') THEN 'topnovostroek.ru'
    WHEN LOWER(crm_advertising_source) = 'topnovostroek.ru тгб' THEN 'topnovostroek.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'vsenovostroyki') AND LOWER(utm_medium) = 'cpm' THEN 'vsenovostroyki.ru '
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'irn_metrinfo_realsearch') AND LOWER(utm_medium) = 'statika' THEN 'IRN. Metrinfo, Realsearch'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'kvartirny-control') AND LOWER(utm_medium) = 'statika' THEN 'kvartirny-control'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mskguru') AND LOWER(utm_medium) = 'statika' THEN 'mskguru.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'naydikvartiru') AND LOWER(utm_medium) = 'statika' THEN 'Naydikvartiru.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'elitnoe') AND LOWER(utm_medium) = 'statika' THEN 'elitnoe.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'mirkvartir') AND LOWER(utm_medium) = 'statika' THEN 'Mirkvartir'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'eip') AND LOWER(utm_medium) = 'statika' THEN 'eip.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'gdeetotdom') AND LOWER(utm_medium) = 'statika' THEN 'Gdeetotdom.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroy-rf') AND LOWER(utm_medium) = 'statika' THEN 'novostroy-rf.ru'
    WHEN REGEXP_CONTAINS(LOWER(utm_source),r'novostroyki.pro') AND LOWER(utm_medium) IN ('cpm','statika') THEN 'novostroyki.pro.'

    ELSE 'NaN'
  END